name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/vf_ldce/PP-VF-App-Portal
            git pull origin main
            npm install
            npm run build
            pm2 restart vf-ldce
            if ! sudo cmp -s nginx/default.conf /etc/nginx/sites-available/default; then
              sudo cp nginx/default.conf /etc/nginx/sites-available/default
              sudo nginx -t
              sudo systemctl reload nginx
            fi
            sudo chmod o+x /home/vf_ldce
